# Generated by Django 4.1.7 on 2023-03-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('Asian', 'Asian'), ('Hispanic', 'Hispanic'), ('Other', 'Other')], max_length=20),
        ),
    ]
