# Generated by Django 4.1.7 on 2023-03-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0003_alter_athlete_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=4),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sport',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
